// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function make(source) {
  return {
    source: source,
    pos: 0,
    line: 1,
    col: 1
  };
}

function isAtEnd(l) {
  return l.pos >= l.source.length;
}

function peek(l) {
  if (isAtEnd(l)) {
    return;
  } else {
    return l.source[l.pos];
  }
}

function peekNext(l) {
  if ((l.pos + 1 | 0) >= l.source.length) {
    return;
  } else {
    return l.source[l.pos + 1 | 0];
  }
}

function advance(l) {
  let ch = Stdlib_Option.getOr(l.source[l.pos], "");
  l.pos = l.pos + 1 | 0;
  if (ch === "\n") {
    l.line = l.line + 1 | 0;
    l.col = 1;
  } else {
    l.col = l.col + 1 | 0;
  }
  return ch;
}

function currentLoc(l) {
  return {
    line: l.line,
    col: l.col
  };
}

function skipWhitespaceAndComments(l) {
  while (true) {
    if (isAtEnd(l)) {
      return;
    }
    let match = peek(l);
    if (match === undefined) {
      return;
    }
    switch (match) {
      case "/" :
        let match$1 = peekNext(l);
        if (match$1 === undefined) {
          return;
        }
        switch (match$1) {
          case "*" :
            advance(l);
            advance(l);
            let skipBlock = () => {
              while (true) {
                if (isAtEnd(l)) {
                  return;
                }
                let match = peek(l);
                if (match === undefined) {
                  return;
                }
                if (match === "*") {
                  advance(l);
                  let match$1 = peek(l);
                  if (match$1 !== undefined) {
                    if (match$1 === "/") {
                      advance(l);
                      return;
                    }
                    continue;
                  }
                  continue;
                }
                advance(l);
                continue;
              };
            };
            skipBlock();
            continue;
          case "/" :
            advance(l);
            advance(l);
            let skipLine = () => {
              while (true) {
                if (isAtEnd(l)) {
                  return;
                }
                let match = peek(l);
                if (match === undefined) {
                  return;
                }
                if (match === "\n") {
                  advance(l);
                  return;
                }
                advance(l);
                continue;
              };
            };
            skipLine();
            continue;
          default:
            return;
        }
      case " " :
      case "\n" :
      case "\r" :
      case "\t" :
        advance(l);
        continue;
      default:
        return;
    }
  };
}

function isAlpha(ch) {
  if (ch >= "a" && ch <= "z" || ch >= "A" && ch <= "Z") {
    return true;
  } else {
    return ch === "_";
  }
}

function isDigit(ch) {
  if (ch >= "0") {
    return ch <= "9";
  } else {
    return false;
  }
}

function isAlphaNumeric(ch) {
  if (isAlpha(ch)) {
    return true;
  } else {
    return isDigit(ch);
  }
}

function readIdentOrKeyword(l) {
  let start = l.pos;
  while (!isAtEnd(l) && isAlphaNumeric(Stdlib_Option.getOr(peek(l), " "))) {
    advance(l);
  };
  let text = l.source.slice(start, l.pos);
  if (text === "region" && !isAtEnd(l) && Primitive_object.equal(peek(l), ".")) {
    let savedPos = l.pos;
    let savedLine = l.line;
    let savedCol = l.col;
    advance(l);
    let methodStart = l.pos;
    while (!isAtEnd(l) && isAlphaNumeric(Stdlib_Option.getOr(peek(l), " "))) {
      advance(l);
    };
    let method = l.source.slice(methodStart, l.pos);
    switch (method) {
      case "alloc" :
        return "RegionAlloc";
      case "free" :
        return "RegionFree";
      case "get" :
        return "RegionGet";
      case "scan" :
        return "RegionScan";
      case "set" :
        return "RegionSet";
      default:
        l.pos = savedPos;
        l.line = savedLine;
        l.col = savedCol;
        return "Region";
    }
  } else {
    switch (text) {
      case "Alloc" :
        return "EffAlloc";
      case "Free" :
        return "EffFree";
      case "Read" :
        return "EffRead";
      case "ReadRegion" :
        return "EffReadRegion";
      case "Write" :
        return "EffWrite";
      case "WriteRegion" :
        return "EffWriteRegion";
      case "across" :
        return "Across";
      case "alias_freedom" :
        return "TacticAliasFreedom";
      case "align" :
        return "Align";
      case "at" :
        return "At";
      case "bool" :
        return "TyBool";
      case "bounds_check" :
        return "TacticBoundsCheck";
      case "by" :
        return "By";
      case "cast" :
        return "Cast";
      case "effect_purity" :
        return "TacticEffectPurity";
      case "effects" :
        return "Effects";
      case "else" :
        return "Else";
      case "export" :
        return "Export";
      case "f32" :
        return "TyF32";
      case "f64" :
        return "TyF64";
      case "false" :
        return "False";
      case "fn" :
        return "Fn";
      case "from" :
        return "From";
      case "given" :
        return "Given";
      case "holds" :
        return "Holds";
      case "i16" :
        return "TyI16";
      case "i32" :
        return "TyI32";
      case "i64" :
        return "TyI64";
      case "i8" :
        return "TyI8";
      case "if" :
        return "If";
      case "import" :
        return "Import";
      case "induction" :
        return "TacticInduction";
      case "initial" :
        return "Initial";
      case "invariant" :
        return "Invariant";
      case "is_null" :
        return "IsNull";
      case "is_valid" :
        return "IsValid";
      case "let" :
        return "Let";
      case "lifetime" :
        return "Lifetime";
      case "linearity" :
        return "TacticLinearity";
      case "maximum" :
        return "Maximum";
      case "memory" :
        return "Memory";
      case "mut" :
        return "Mut";
      case "null" :
        return "Null";
      case "offsetof" :
        return "Offsetof";
      case "opt" :
        return "Opt";
      case "own" :
        return "Own";
      case "place" :
        return "Place";
      case "proof" :
        return "Proof";
      case "ptr" :
        return "Ptr";
      case "ref" :
        return "Ref";
      case "region" :
        return "Region";
      case "return" :
        return "Return";
      case "rewrite" :
        return "TacticRewrite";
      case "shared" :
        return "Shared";
      case "show" :
        return "Show";
      case "sizeof" :
        return "Sizeof";
      case "static_assert" :
        return "StaticAssert";
      case "true" :
        return "True";
      case "typeof" :
        return "Typeof";
      case "u16" :
        return "TyU16";
      case "u32" :
        return "TyU32";
      case "u64" :
        return "TyU64";
      case "u8" :
        return "TyU8";
      case "union" :
        return "Union";
      case "unique" :
        return "Unique";
      case "void" :
        return "Void";
      case "where" :
        return "Where";
      case "while" :
        return "While";
      default:
        return {
          TAG: "Ident",
          _0: text
        };
    }
  }
}

function readNumber(l) {
  let start = l.pos;
  let isNegative = Primitive_object.equal(peek(l), "-");
  if (isNegative) {
    advance(l);
  }
  while (!isAtEnd(l) && isDigit(Stdlib_Option.getOr(peek(l), " "))) {
    advance(l);
  };
  if (!isAtEnd(l) && Primitive_object.equal(peek(l), ".") && isDigit(Stdlib_Option.getOr(peekNext(l), " "))) {
    advance(l);
    while (!isAtEnd(l) && isDigit(Stdlib_Option.getOr(peek(l), " "))) {
      advance(l);
    };
    let text = l.source.slice(start, l.pos);
    return {
      TAG: "FloatLiteral",
      _0: Stdlib_Option.getOr(Stdlib_Float.fromString(text), 0.0)
    };
  }
  let text$1 = l.source.slice(start, l.pos);
  return {
    TAG: "IntLiteral",
    _0: Stdlib_Option.getOr(Stdlib_Int.fromString(text$1, undefined), 0)
  };
}

function readString(l) {
  advance(l);
  let start = l.pos;
  while (!isAtEnd(l) && Primitive_object.notequal(peek(l), "\"")) {
    advance(l);
  };
  let text = l.source.slice(start, l.pos);
  if (!isAtEnd(l)) {
    advance(l);
  }
  return {
    TAG: "StringLiteral",
    _0: text
  };
}

function nextToken(l) {
  skipWhitespaceAndComments(l);
  if (isAtEnd(l)) {
    return {
      value: "EOF",
      loc: currentLoc(l)
    };
  }
  let startLoc = currentLoc(l);
  let ch = Stdlib_Option.getOr(peek(l), " ");
  let tok;
  if (isAlpha(ch)) {
    tok = readIdentOrKeyword(l);
  } else if (isDigit(ch)) {
    tok = readNumber(l);
  } else if (ch === "\"") {
    tok = readString(l);
  } else if (ch === "'") {
    advance(l);
    if (ch === "s" && !isAtEnd(l)) {
      let nameStart = l.pos;
      while (!isAtEnd(l) && isAlphaNumeric(Stdlib_Option.getOr(peek(l), " "))) {
        advance(l);
      };
      let name = l.source.slice(nameStart, l.pos);
      tok = {
        TAG: "LifetimeName",
        _0: name
      };
    } else {
      let nameStart$1 = l.pos;
      while (!isAtEnd(l) && isAlphaNumeric(Stdlib_Option.getOr(peek(l), " "))) {
        advance(l);
      };
      let name$1 = l.source.slice(nameStart$1, l.pos);
      tok = {
        TAG: "LifetimeName",
        _0: name$1
      };
    }
  } else {
    advance(l);
    switch (ch) {
      case "!" :
        if (!isAtEnd(l) && Primitive_object.equal(peek(l), "=")) {
          advance(l);
          tok = "BangEq";
        } else {
          tok = "Bang";
        }
        break;
      case "$" :
        tok = "Dollar";
        break;
      case "%" :
        tok = "Percent";
        break;
      case "&" :
        if (!isAtEnd(l) && Primitive_object.equal(peek(l), "&")) {
          advance(l);
          tok = "AmpAmp";
        } else if (!isAtEnd(l) && Primitive_object.equal(peek(l), "m")) {
          let savedPos = l.pos;
          let savedCol = l.col;
          let savedLine = l.line;
          advance(l);
          if (!isAtEnd(l) && Primitive_object.equal(peek(l), "u")) {
            advance(l);
            if (!isAtEnd(l) && Primitive_object.equal(peek(l), "t")) {
              advance(l);
              if (isAtEnd(l) || !isAlphaNumeric(Stdlib_Option.getOr(peek(l), " "))) {
                tok = "AmpMut";
              } else {
                l.pos = savedPos;
                l.col = savedCol;
                l.line = savedLine;
                tok = "Ampersand";
              }
            } else {
              l.pos = savedPos;
              l.col = savedCol;
              l.line = savedLine;
              tok = "Ampersand";
            }
          } else {
            l.pos = savedPos;
            l.col = savedCol;
            l.line = savedLine;
            tok = "Ampersand";
          }
        } else {
          tok = "Ampersand";
        }
        break;
      case "(" :
        tok = "LParen";
        break;
      case ")" :
        tok = "RParen";
        break;
      case "*" :
        tok = "Star";
        break;
      case "+" :
        tok = "Plus";
        break;
      case "," :
        tok = "Comma";
        break;
      case "-" :
        if (!isAtEnd(l) && Primitive_object.equal(peek(l), ">")) {
          advance(l);
          tok = "Arrow";
        } else if (!isAtEnd(l) && isDigit(Stdlib_Option.getOr(peek(l), " "))) {
          l.pos = l.pos - 1 | 0;
          l.col = l.col - 1 | 0;
          tok = readNumber(l);
        } else {
          tok = "Minus";
        }
        break;
      case "." :
        tok = "Dot";
        break;
      case "/" :
        tok = "Slash";
        break;
      case ":" :
        if (!isAtEnd(l) && Primitive_object.equal(peek(l), ":")) {
          advance(l);
          tok = "ColonColon";
        } else {
          tok = "Colon";
        }
        break;
      case ";" :
        tok = "Semicolon";
        break;
      case "<" :
        if (!isAtEnd(l) && Primitive_object.equal(peek(l), "=")) {
          advance(l);
          tok = "LtEq";
        } else if (!isAtEnd(l) && Primitive_object.equal(peek(l), "<")) {
          advance(l);
          tok = "LShift";
        } else {
          tok = "LAngle";
        }
        break;
      case "=" :
        if (!isAtEnd(l) && Primitive_object.equal(peek(l), "=")) {
          advance(l);
          tok = "EqEq";
        } else {
          tok = "Eq";
        }
        break;
      case ">" :
        if (!isAtEnd(l) && Primitive_object.equal(peek(l), "=")) {
          advance(l);
          tok = "GtEq";
        } else if (!isAtEnd(l) && Primitive_object.equal(peek(l), ">")) {
          advance(l);
          tok = "RShift";
        } else {
          tok = "RAngle";
        }
        break;
      case "?" :
        tok = "Question";
        break;
      case "@" :
        tok = "At";
        break;
      case "[" :
        tok = "LBracket";
        break;
      case "]" :
        tok = "RBracket";
        break;
      case "^" :
        tok = "Caret";
        break;
      case "{" :
        tok = "LBrace";
        break;
      case "|" :
        if (!isAtEnd(l) && Primitive_object.equal(peek(l), "|")) {
          advance(l);
          tok = "PipePipe";
        } else {
          tok = "Pipe";
        }
        break;
      case "}" :
        tok = "RBrace";
        break;
      case "~" :
        tok = "Tilde";
        break;
      default:
        tok = {
          TAG: "Ident",
          _0: ch
        };
    }
  }
  return {
    value: tok,
    loc: startLoc
  };
}

function tokenize(source) {
  let l = make(source);
  let tokens = [];
  let loop = () => {
    while (true) {
      let tok = nextToken(l);
      tokens.push(tok);
      if (tok.value === "EOF") {
        return;
      }
      continue;
    };
  };
  loop();
  return tokens;
}

export {
  make,
  isAtEnd,
  peek,
  peekNext,
  advance,
  currentLoc,
  skipWhitespaceAndComments,
  isAlpha,
  isDigit,
  isAlphaNumeric,
  readIdentOrKeyword,
  readNumber,
  readString,
  nextToken,
  tokenize,
}
/* No side effect */
