// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lexer from "./Lexer.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function make(source) {
  return {
    tokens: Lexer.tokenize(source),
    pos: 0
  };
}

function current(p) {
  if (p.pos < p.tokens.length) {
    return Stdlib_Option.getOr(p.tokens[p.pos], {
      value: "EOF",
      loc: {
        line: 0,
        col: 0
      }
    });
  } else {
    return {
      value: "EOF",
      loc: {
        line: 0,
        col: 0
      }
    };
  }
}

function peek(p) {
  return current(p).value;
}

function loc(p) {
  return current(p).loc;
}

function advance(p) {
  if (p.pos < p.tokens.length) {
    p.pos = p.pos + 1 | 0;
    return;
  }
}

function expect(p, expected) {
  if (Primitive_object.equal(current(p).value, expected)) {
    advance(p);
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: `Expected token, found something else`,
        loc: current(p).loc
      }
    };
  }
}

function expectIdent(p) {
  let name = current(p).value;
  if (typeof name !== "object") {
    return {
      TAG: "Error",
      _0: {
        message: "Expected identifier",
        loc: current(p).loc
      }
    };
  }
  if (name.TAG !== "Ident") {
    return {
      TAG: "Error",
      _0: {
        message: "Expected identifier",
        loc: current(p).loc
      }
    };
  }
  advance(p);
  return {
    TAG: "Ok",
    _0: name._0
  };
}

function expectInt(p) {
  let n = current(p).value;
  if (typeof n !== "object") {
    return {
      TAG: "Error",
      _0: {
        message: "Expected integer literal",
        loc: current(p).loc
      }
    };
  }
  if (n.TAG !== "IntLiteral") {
    return {
      TAG: "Error",
      _0: {
        message: "Expected integer literal",
        loc: current(p).loc
      }
    };
  }
  advance(p);
  return {
    TAG: "Ok",
    _0: n._0
  };
}

function expectString(p) {
  let s = current(p).value;
  if (typeof s !== "object") {
    return {
      TAG: "Error",
      _0: {
        message: "Expected string literal",
        loc: current(p).loc
      }
    };
  }
  if (s.TAG !== "StringLiteral") {
    return {
      TAG: "Error",
      _0: {
        message: "Expected string literal",
        loc: current(p).loc
      }
    };
  }
  advance(p);
  return {
    TAG: "Ok",
    _0: s._0
  };
}

function located(p, node) {
  return {
    node: node,
    loc: current(p).loc
  };
}

function parsePrimitiveType(p) {
  let match = current(p).value;
  let typ;
  if (typeof match !== "object") {
    switch (match) {
      case "TyI8" :
        typ = "I8";
        break;
      case "TyI16" :
        typ = "I16";
        break;
      case "TyI32" :
        typ = "I32";
        break;
      case "TyI64" :
        typ = "I64";
        break;
      case "TyU8" :
        typ = "U8";
        break;
      case "TyU16" :
        typ = "U16";
        break;
      case "TyU32" :
        typ = "U32";
        break;
      case "TyU64" :
        typ = "U64";
        break;
      case "TyF32" :
        typ = "F32";
        break;
      case "TyF64" :
        typ = "F64";
        break;
      case "TyBool" :
        typ = "Bool";
        break;
      default:
        typ = undefined;
    }
  } else {
    typ = undefined;
  }
  if (typ !== undefined) {
    advance(p);
    return {
      TAG: "Ok",
      _0: typ
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "Expected primitive type",
        loc: current(p).loc
      }
    };
  }
}

function parseFieldType(p) {
  let startLoc = current(p).loc;
  let match = current(p).value;
  if (typeof match !== "object") {
    switch (match) {
      case "At" :
        advance(p);
        let name = expectIdent(p);
        if (name.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "RegionRef",
                _0: name._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: name._0
          };
        }
      case "Union" :
        advance(p);
        expect(p, "LBrace");
        let variants = [];
        let parseVariants = () => {
          while (true) {
            if (current(p).value === "RBrace") {
              return {
                TAG: "Ok",
                _0: undefined
              };
            }
            let tag = expectIdent(p);
            if (tag.TAG !== "Ok") {
              return {
                TAG: "Error",
                _0: tag._0
              };
            }
            let e = expect(p, "Colon");
            if (e.TAG !== "Ok") {
              return {
                TAG: "Error",
                _0: e._0
              };
            }
            let vType = parseFieldType(p);
            if (vType.TAG !== "Ok") {
              return {
                TAG: "Error",
                _0: vType._0
              };
            }
            expect(p, "Semicolon");
            variants.push({
              node: {
                tag: tag._0,
                variantType: vType._0
              },
              loc: startLoc
            });
            continue;
          };
        };
        let e = parseVariants();
        if (e.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: e._0
          };
        }
        let e$1 = expect(p, "RBrace");
        if (e$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "UnionType",
                _0: variants
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$1._0
          };
        }
      case "Ptr" :
        advance(p);
        expect(p, "LAngle");
        let inner = parseFieldType(p);
        if (inner.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: inner._0
          };
        }
        let e$2 = expect(p, "RAngle");
        if (e$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "PointerType",
                _0: "PtrOwning",
                _1: inner._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$2._0
          };
        }
      case "Ref" :
        advance(p);
        expect(p, "LAngle");
        let inner$1 = parseFieldType(p);
        if (inner$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: inner$1._0
          };
        }
        let e$3 = expect(p, "RAngle");
        if (e$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "PointerType",
                _0: "RefBorrow",
                _1: inner$1._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$3._0
          };
        }
      case "Unique" :
        advance(p);
        expect(p, "LAngle");
        let inner$2 = parseFieldType(p);
        if (inner$2.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: inner$2._0
          };
        }
        let e$4 = expect(p, "RAngle");
        if (e$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "PointerType",
                _0: "UniqueExcl",
                _1: inner$2._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$4._0
          };
        }
      case "Opt" :
        advance(p);
        expect(p, "LAngle");
        let inner$3 = parseFieldType(p);
        if (inner$3.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: inner$3._0
          };
        }
        let e$5 = expect(p, "RAngle");
        if (e$5.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "OptionalType",
                _0: inner$3._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$5._0
          };
        }
    }
  }
  let prim = parsePrimitiveType(p);
  if (prim.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "Expected field type",
        loc: startLoc
      }
    };
  }
  let prim$1 = prim._0;
  if (current(p).value !== "LBracket") {
    return {
      TAG: "Ok",
      _0: {
        node: {
          TAG: "Primitive",
          _0: prim$1
        },
        loc: startLoc
      }
    };
  }
  advance(p);
  let sizeExpr = parseExprPrec(p, 0);
  if (sizeExpr.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: sizeExpr._0
    };
  }
  let e$6 = expect(p, "RBracket");
  if (e$6.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        node: {
          TAG: "ArrayFieldType",
          _0: {
            node: {
              TAG: "Primitive",
              _0: prim$1
            },
            loc: startLoc
          },
          _1: sizeExpr._0
        },
        loc: startLoc
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e$6._0
    };
  }
}

function parsePrimary(p) {
  let startLoc = current(p).loc;
  let n = current(p).value;
  if (typeof n !== "object") {
    switch (n) {
      case "True" :
        advance(p);
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "BoolLit",
              _0: true
            },
            loc: startLoc
          }
        };
      case "False" :
        advance(p);
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "BoolLit",
              _0: false
            },
            loc: startLoc
          }
        };
      case "Null" :
        advance(p);
        return {
          TAG: "Ok",
          _0: {
            node: "NullLit",
            loc: startLoc
          }
        };
      case "Sizeof" :
        advance(p);
        expect(p, "LParen");
        let name = expectIdent(p);
        if (name.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: name._0
          };
        }
        let e = expect(p, "RParen");
        if (e.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "SizeofExpr",
                _0: name._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e._0
          };
        }
      case "IsValid" :
        advance(p);
        expect(p, "LParen");
        expect(p, "Dollar");
        let name$1 = expectIdent(p);
        if (name$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: name$1._0
          };
        }
        let e$1 = expect(p, "RParen");
        if (e$1.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "IsValidExpr",
                _0: name$1._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$1._0
          };
        }
      case "IsNull" :
        advance(p);
        expect(p, "LParen");
        let inner = parseExprPrec(p, 0);
        if (inner.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: inner._0
          };
        }
        let e$2 = expect(p, "RParen");
        if (e$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "IsNullExpr",
                _0: inner._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$2._0
          };
        }
      case "Cast" :
        advance(p);
        expect(p, "LAngle");
        let ty = parseFieldType(p);
        if (ty.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: ty._0
          };
        }
        expect(p, "RAngle");
        expect(p, "LParen");
        let inner$1 = parseExprPrec(p, 0);
        if (inner$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: inner$1._0
          };
        }
        let e$3 = expect(p, "RParen");
        if (e$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "CastExpr",
                _0: ty._0,
                _1: inner$1._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$3._0
          };
        }
      case "LParen" :
        advance(p);
        let inner$2 = parseExprPrec(p, 0);
        if (inner$2.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: inner$2._0
          };
        }
        let e$4 = expect(p, "RParen");
        if (e$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "ParenExpr",
                _0: inner$2._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$4._0
          };
        }
      case "Dollar" :
        advance(p);
        let name$2 = expectIdent(p);
        if (name$2.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "RegionVar",
                _0: name$2._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: name$2._0
          };
        }
      case "Bang" :
        advance(p);
        let inner$3 = parsePrimary(p);
        if (inner$3.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "UnaryOp",
                _0: "Not",
                _1: inner$3._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: inner$3._0
          };
        }
      case "Tilde" :
        advance(p);
        let inner$4 = parsePrimary(p);
        if (inner$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "UnaryOp",
                _0: "BitNot",
                _1: inner$4._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: inner$4._0
          };
        }
      case "Minus" :
        advance(p);
        let inner$5 = parsePrimary(p);
        if (inner$5.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "UnaryOp",
                _0: "Neg",
                _1: inner$5._0
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: inner$5._0
          };
        }
      default:
        return {
          TAG: "Error",
          _0: {
            message: "Expected expression",
            loc: startLoc
          }
        };
    }
  } else {
    switch (n.TAG) {
      case "IntLiteral" :
        advance(p);
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "IntLit",
              _0: n._0
            },
            loc: startLoc
          }
        };
      case "FloatLiteral" :
        advance(p);
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "FloatLit",
              _0: n._0
            },
            loc: startLoc
          }
        };
      case "StringLiteral" :
        advance(p);
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "StringLit",
              _0: n._0
            },
            loc: startLoc
          }
        };
      case "Ident" :
        let name$3 = n._0;
        advance(p);
        if (current(p).value !== "LParen") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "Identifier",
                _0: name$3
              },
              loc: startLoc
            }
          };
        }
        advance(p);
        let args = [];
        let parseArgs = () => {
          while (true) {
            if (current(p).value === "RParen") {
              return {
                TAG: "Ok",
                _0: undefined
              };
            }
            let arg = parseExprPrec(p, 0);
            if (arg.TAG !== "Ok") {
              return {
                TAG: "Error",
                _0: arg._0
              };
            }
            args.push(arg._0);
            if (current(p).value === "Comma") {
              advance(p);
            }
            continue;
          };
        };
        let e$5 = parseArgs();
        if (e$5.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: e$5._0
          };
        }
        let e$6 = expect(p, "RParen");
        if (e$6.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "CallExpr",
                _0: name$3,
                _1: args
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$6._0
          };
        }
      default:
        return {
          TAG: "Error",
          _0: {
            message: "Expected expression",
            loc: startLoc
          }
        };
    }
  }
}

function parseExprPrec(p, minPrec) {
  let left = parsePrimary(p);
  if (left.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: left._0
    };
  }
  let _left = left._0;
  while (true) {
    let left$1 = _left;
    let match = binOpPrecedence(current(p).value);
    if (match === undefined) {
      return {
        TAG: "Ok",
        _0: left$1
      };
    }
    let prec = match[1];
    if (prec < minPrec) {
      return {
        TAG: "Ok",
        _0: left$1
      };
    }
    advance(p);
    let right = parseExprPrec(p, prec + 1 | 0);
    if (right.TAG !== "Ok") {
      return {
        TAG: "Error",
        _0: right._0
      };
    }
    _left = {
      node: {
        TAG: "BinOp",
        _0: left$1,
        _1: match[0],
        _2: right._0
      },
      loc: left$1.loc
    };
    continue;
  };
}

function binOpPrecedence(tok) {
  if (typeof tok === "object") {
    return;
  }
  switch (tok) {
    case "LAngle" :
      return [
        "Lt",
        7
      ];
    case "RAngle" :
      return [
        "Gt",
        7
      ];
    case "Ampersand" :
      return [
        "BitAnd",
        5
      ];
    case "Pipe" :
      return [
        "BitOr",
        3
      ];
    case "Plus" :
      return [
        "Add",
        9
      ];
    case "Minus" :
      return [
        "Sub",
        9
      ];
    case "Star" :
      return [
        "Mul",
        10
      ];
    case "Slash" :
      return [
        "Div",
        10
      ];
    case "Percent" :
      return [
        "Mod",
        10
      ];
    case "EqEq" :
      return [
        "Eq",
        6
      ];
    case "BangEq" :
      return [
        "NotEq",
        6
      ];
    case "LtEq" :
      return [
        "LtEq",
        7
      ];
    case "GtEq" :
      return [
        "GtEq",
        7
      ];
    case "AmpAmp" :
      return [
        "And",
        2
      ];
    case "PipePipe" :
      return [
        "Or",
        1
      ];
    case "Caret" :
      return [
        "BitXor",
        4
      ];
    case "LShift" :
      return [
        "Shl",
        8
      ];
    case "RShift" :
      return [
        "Shr",
        8
      ];
    default:
      return;
  }
}

function parseExpr(p) {
  return parseExprPrec(p, 0);
}

function parseRegionTarget(p) {
  expect(p, "Dollar");
  let name = expectIdent(p);
  if (name.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: name._0
    };
  }
  let name$1 = name._0;
  if (current(p).value !== "LBracket") {
    return {
      TAG: "Ok",
      _0: {
        name: name$1,
        index: undefined
      }
    };
  }
  advance(p);
  let idx = parseExprPrec(p, 0);
  if (idx.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: idx._0
    };
  }
  let e = expect(p, "RBracket");
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        name: name$1,
        index: idx._0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
}

function parseFieldPath(p) {
  let segments = [];
  let loop = () => {
    while (true) {
      let match = current(p).value;
      if (typeof match === "object") {
        return {
          TAG: "Ok",
          _0: segments
        };
      }
      switch (match) {
        case "LBracket" :
          advance(p);
          let idx = parseExprPrec(p, 0);
          if (idx.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: idx._0
            };
          }
          let e = expect(p, "RBracket");
          if (e.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: e._0
            };
          }
          segments.push({
            TAG: "IndexAccess",
            _0: idx._0
          });
          continue;
        case "Dot" :
          advance(p);
          let name = expectIdent(p);
          if (name.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: name._0
            };
          }
          segments.push({
            TAG: "FieldAccess",
            _0: name._0
          });
          continue;
        default:
          return {
            TAG: "Ok",
            _0: segments
          };
      }
    };
  };
  return loop();
}

function parseStatement(p) {
  let startLoc = current(p).loc;
  let match = current(p).value;
  if (typeof match !== "object") {
    switch (match) {
      case "Let" :
        advance(p);
        let isMut = current(p).value === "Mut";
        if (isMut) {
          advance(p);
        }
        let name = expectIdent(p);
        if (name.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: name._0
          };
        }
        let typeAnn;
        if (current(p).value === "Colon") {
          advance(p);
          let ty = parseFieldType(p);
          typeAnn = ty.TAG === "Ok" ? ty._0 : undefined;
        } else {
          typeAnn = undefined;
        }
        let e = expect(p, "Eq");
        if (e.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: e._0
          };
        }
        let init = parseExprPrec(p, 0);
        if (init.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: init._0
          };
        }
        expect(p, "Semicolon");
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "LetStmt",
              _0: {
                isMutable: isMut,
                name: name._0,
                typeAnnotation: typeAnn,
                initializer: init._0
              }
            },
            loc: startLoc
          }
        };
      case "If" :
        advance(p);
        let cond = parseExprPrec(p, 0);
        if (cond.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: cond._0
          };
        }
        let e$1 = expect(p, "LBrace");
        if (e$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: e$1._0
          };
        }
        let thenBody = parseBlock(p);
        if (thenBody.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: thenBody._0
          };
        }
        let e$2 = expect(p, "RBrace");
        if (e$2.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: e$2._0
          };
        }
        let elseBody;
        if (current(p).value === "Else") {
          advance(p);
          expect(p, "LBrace");
          let body = parseBlock(p);
          if (body.TAG === "Ok") {
            expect(p, "RBrace");
            elseBody = body._0;
          } else {
            elseBody = undefined;
          }
        } else {
          elseBody = undefined;
        }
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "IfStmt",
              _0: {
                condition: cond._0,
                thenBranch: thenBody._0,
                elseBranch: elseBody
              }
            },
            loc: startLoc
          }
        };
      case "While" :
        advance(p);
        let cond$1 = parseExprPrec(p, 0);
        if (cond$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: cond$1._0
          };
        }
        let e$3 = expect(p, "LBrace");
        if (e$3.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: e$3._0
          };
        }
        let body$1 = parseBlock(p);
        if (body$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: body$1._0
          };
        }
        let e$4 = expect(p, "RBrace");
        if (e$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "WhileStmt",
                _0: {
                  condition: cond$1._0,
                  body: body$1._0
                }
              },
              loc: startLoc
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: e$4._0
          };
        }
      case "Return" :
        advance(p);
        if (current(p).value === "Semicolon") {
          advance(p);
          return {
            TAG: "Ok",
            _0: {
              node: {
                TAG: "ReturnStmt",
                _0: undefined
              },
              loc: startLoc
            }
          };
        }
        let value = parseExprPrec(p, 0);
        if (value.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: value._0
          };
        }
        expect(p, "Semicolon");
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "ReturnStmt",
              _0: value._0
            },
            loc: startLoc
          }
        };
      case "RegionGet" :
        advance(p);
        let target = parseRegionTarget(p);
        if (target.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: target._0
          };
        }
        let path = parseFieldPath(p);
        if (path.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: path._0
          };
        }
        let binding;
        if (current(p).value === "Arrow") {
          advance(p);
          let name$1 = expectIdent(p);
          binding = name$1.TAG === "Ok" ? name$1._0 : undefined;
        } else {
          binding = undefined;
        }
        expect(p, "Semicolon");
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "RegionGetStmt",
              _0: {
                target: target._0,
                fieldPath: path._0,
                binding: binding
              }
            },
            loc: startLoc
          }
        };
      case "RegionSet" :
        advance(p);
        let target$1 = parseRegionTarget(p);
        if (target$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: target$1._0
          };
        }
        let path$1 = parseFieldPath(p);
        if (path$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: path$1._0
          };
        }
        let e$5 = expect(p, "Comma");
        if (e$5.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: e$5._0
          };
        }
        let value$1 = parseExprPrec(p, 0);
        if (value$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: value$1._0
          };
        }
        expect(p, "Semicolon");
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "RegionSetStmt",
              _0: {
                target: target$1._0,
                fieldPath: path$1._0,
                value: value$1._0
              }
            },
            loc: startLoc
          }
        };
      case "RegionAlloc" :
        advance(p);
        let regionName = expectIdent(p);
        if (regionName.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: regionName._0
          };
        }
        let inits = [];
        if (current(p).value === "LBrace") {
          advance(p);
          let parseInits = () => {
            while (true) {
              if (current(p).value === "RBrace") {
                return {
                  TAG: "Ok",
                  _0: undefined
                };
              }
              let fieldName = expectIdent(p);
              if (fieldName.TAG !== "Ok") {
                return {
                  TAG: "Error",
                  _0: fieldName._0
                };
              }
              let e = expect(p, "Eq");
              if (e.TAG !== "Ok") {
                return {
                  TAG: "Error",
                  _0: e._0
                };
              }
              let value = parseExprPrec(p, 0);
              if (value.TAG !== "Ok") {
                return {
                  TAG: "Error",
                  _0: value._0
                };
              }
              inits.push([
                fieldName._0,
                value._0
              ]);
              if (current(p).value === "Comma") {
                advance(p);
              }
              continue;
            };
          };
          let e$6 = parseInits();
          if (e$6.TAG === "Ok") {
            expect(p, "RBrace");
          }
        }
        let e$7 = expect(p, "Arrow");
        if (e$7.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: e$7._0
          };
        }
        let binding$1 = expectIdent(p);
        if (binding$1.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: binding$1._0
          };
        }
        expect(p, "Semicolon");
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "RegionAllocStmt",
              _0: {
                regionName: regionName._0,
                initializers: inits,
                binding: binding$1._0
              }
            },
            loc: startLoc
          }
        };
      case "RegionFree" :
        advance(p);
        expect(p, "Dollar");
        let name$2 = expectIdent(p);
        if (name$2.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: name$2._0
          };
        }
        expect(p, "Semicolon");
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "RegionFreeStmt",
              _0: name$2._0
            },
            loc: startLoc
          }
        };
      case "StaticAssert" :
        advance(p);
        let prop = parseExprPrec(p, 0);
        if (prop.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: prop._0
          };
        }
        expect(p, "Semicolon");
        return {
          TAG: "Ok",
          _0: {
            node: {
              TAG: "StaticAssertStmt",
              _0: prop._0
            },
            loc: startLoc
          }
        };
    }
  }
  let expr = parseExprPrec(p, 0);
  if (expr.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: expr._0
    };
  }
  expect(p, "Semicolon");
  return {
    TAG: "Ok",
    _0: {
      node: {
        TAG: "ExprStmt",
        _0: expr._0
      },
      loc: startLoc
    }
  };
}

function parseBlock(p) {
  let stmts = [];
  let loop = () => {
    while (true) {
      if (current(p).value === "RBrace" || current(p).value === "EOF") {
        return {
          TAG: "Ok",
          _0: stmts
        };
      }
      let stmt = parseStatement(p);
      if (stmt.TAG !== "Ok") {
        return {
          TAG: "Error",
          _0: stmt._0
        };
      }
      stmts.push(stmt._0);
      continue;
    };
  };
  return loop();
}

function parseFieldDecl(p) {
  let startLoc = current(p).loc;
  let name = expectIdent(p);
  if (name.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: name._0
    };
  }
  let e = expect(p, "Colon");
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let ty = parseFieldType(p);
  if (ty.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: ty._0
    };
  }
  let constraints = [];
  if (current(p).value === "Where") {
    advance(p);
    let expr = parseExprPrec(p, 0);
    if (expr.TAG === "Ok") {
      constraints.push({
        node: {
          TAG: "PredicateConstraint",
          _0: "constraint",
          _1: [expr._0]
        },
        loc: startLoc
      });
    }
  }
  expect(p, "Semicolon");
  return {
    TAG: "Ok",
    _0: {
      node: {
        name: name._0,
        fieldType: ty._0,
        constraints: constraints
      },
      loc: startLoc
    }
  };
}

function parseRegionDecl(p) {
  let startLoc = current(p).loc;
  advance(p);
  let name = expectIdent(p);
  if (name.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: name._0
    };
  }
  let instanceCount;
  if (current(p).value === "LBracket") {
    advance(p);
    let count = parseExprPrec(p, 0);
    if (count.TAG === "Ok") {
      expect(p, "RBracket");
      instanceCount = count._0;
    } else {
      instanceCount = undefined;
    }
  } else {
    instanceCount = undefined;
  }
  let e = expect(p, "LBrace");
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let fields = [];
  let alignment = {
    contents: undefined
  };
  let invariants = [];
  let parseBody = () => {
    while (true) {
      let match = current(p).value;
      if (typeof match !== "object") {
        switch (match) {
          case "Where" :
            advance(p);
            while (current(p).value !== "Semicolon" && current(p).value !== "EOF") {
              advance(p);
            };
            expect(p, "Semicolon");
            continue;
          case "Invariant" :
            advance(p);
            expect(p, "LBrace");
            let parseInvariants = () => {
              while (true) {
                if (current(p).value === "RBrace") {
                  return {
                    TAG: "Ok",
                    _0: undefined
                  };
                }
                let invName = expectIdent(p);
                if (invName.TAG !== "Ok") {
                  return {
                    TAG: "Error",
                    _0: invName._0
                  };
                }
                expect(p, "Colon");
                let prop = parseExprPrec(p, 0);
                if (prop.TAG !== "Ok") {
                  return {
                    TAG: "Error",
                    _0: prop._0
                  };
                }
                expect(p, "Semicolon");
                invariants.push({
                  node: {
                    name: invName._0,
                    proposition: prop._0
                  },
                  loc: startLoc
                });
                continue;
              };
            };
            let e = parseInvariants();
            if (e.TAG !== "Ok") {
              return {
                TAG: "Error",
                _0: e._0
              };
            }
            expect(p, "RBrace");
            continue;
          case "Align" :
            advance(p);
            let n = expectInt(p);
            if (n.TAG !== "Ok") {
              return {
                TAG: "Error",
                _0: n._0
              };
            }
            alignment.contents = n._0;
            expect(p, "Semicolon");
            continue;
          case "RBrace" :
            return {
              TAG: "Ok",
              _0: undefined
            };
        }
      }
      let field = parseFieldDecl(p);
      if (field.TAG !== "Ok") {
        return {
          TAG: "Error",
          _0: field._0
        };
      }
      fields.push(field._0);
      continue;
    };
  };
  let e$1 = parseBody();
  if (e$1.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e$1._0
    };
  }
  let e$2 = expect(p, "RBrace");
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        node: {
          TAG: "RegionDecl",
          _0: {
            name: name._0,
            instanceCount: instanceCount,
            fields: fields,
            alignment: alignment.contents,
            invariants: invariants
          }
        },
        loc: startLoc
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e$2._0
    };
  }
}

function parseEffects(p) {
  let effects = [];
  advance(p);
  expect(p, "LBrace");
  let loop = () => {
    while (true) {
      if (current(p).value === "RBrace") {
        return {
          TAG: "Ok",
          _0: undefined
        };
      }
      let startLoc = current(p).loc;
      let match = current(p).value;
      let eff;
      if (typeof match !== "object") {
        switch (match) {
          case "EffRead" :
            advance(p);
            eff = {
              TAG: "Ok",
              _0: "ReadEffect"
            };
            break;
          case "EffWrite" :
            advance(p);
            eff = {
              TAG: "Ok",
              _0: "WriteEffect"
            };
            break;
          case "EffAlloc" :
            advance(p);
            eff = {
              TAG: "Ok",
              _0: "AllocEffect"
            };
            break;
          case "EffFree" :
            advance(p);
            eff = {
              TAG: "Ok",
              _0: "FreeEffect"
            };
            break;
          case "EffReadRegion" :
            advance(p);
            expect(p, "LParen");
            let name = expectIdent(p);
            if (name.TAG === "Ok") {
              expect(p, "RParen");
              eff = {
                TAG: "Ok",
                _0: {
                  TAG: "ReadRegionEffect",
                  _0: name._0
                }
              };
            } else {
              eff = {
                TAG: "Error",
                _0: name._0
              };
            }
            break;
          case "EffWriteRegion" :
            advance(p);
            expect(p, "LParen");
            let name$1 = expectIdent(p);
            if (name$1.TAG === "Ok") {
              expect(p, "RParen");
              eff = {
                TAG: "Ok",
                _0: {
                  TAG: "WriteRegionEffect",
                  _0: name$1._0
                }
              };
            } else {
              eff = {
                TAG: "Error",
                _0: name$1._0
              };
            }
            break;
          default:
            eff = {
              TAG: "Error",
              _0: {
                message: "Expected effect",
                loc: startLoc
              }
            };
        }
      } else {
        eff = {
          TAG: "Error",
          _0: {
            message: "Expected effect",
            loc: startLoc
          }
        };
      }
      if (eff.TAG !== "Ok") {
        return {
          TAG: "Error",
          _0: eff._0
        };
      }
      effects.push({
        node: eff._0,
        loc: startLoc
      });
      if (current(p).value === "Comma") {
        advance(p);
      }
      continue;
    };
  };
  let e = loop();
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  expect(p, "RBrace");
  return {
    TAG: "Ok",
    _0: effects
  };
}

function parseFunctionDecl(p) {
  let startLoc = current(p).loc;
  advance(p);
  let name = expectIdent(p);
  if (name.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: name._0
    };
  }
  expect(p, "LParen");
  let params = [];
  let parseParams = () => {
    while (true) {
      if (current(p).value === "RParen") {
        return {
          TAG: "Ok",
          _0: undefined
        };
      }
      let paramLoc = current(p).loc;
      let paramName = expectIdent(p);
      if (paramName.TAG !== "Ok") {
        return {
          TAG: "Error",
          _0: paramName._0
        };
      }
      let paramName$1 = paramName._0;
      expect(p, "Colon");
      let match = current(p).value;
      let exit = 0;
      if (typeof match !== "object") {
        switch (match) {
          case "Own" :
          case "Ampersand" :
          case "AmpMut" :
            exit = 2;
            break;
          default:
            exit = 1;
        }
      } else {
        exit = 1;
      }
      switch (exit) {
        case 1 :
          let ty = parseFieldType(p);
          if (ty.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: ty._0
            };
          }
          params.push({
            node: {
              name: paramName$1,
              paramType: {
                node: {
                  TAG: "FieldParam",
                  _0: ty._0.node
                },
                loc: paramLoc
              }
            },
            loc: paramLoc
          });
          if (current(p).value === "Comma") {
            advance(p);
          }
          continue;
        case 2 :
          let match$1 = current(p).value;
          let mode;
          if (typeof match$1 !== "object") {
            switch (match$1) {
              case "Own" :
                advance(p);
                mode = "Owning";
                break;
              case "Ampersand" :
                advance(p);
                mode = "SharedBorrow";
                break;
              case "AmpMut" :
                advance(p);
                mode = "MutableBorrow";
                break;
              default:
                mode = "SharedBorrow";
            }
          } else {
            mode = "SharedBorrow";
          }
          expect(p, "Region");
          expect(p, "LAngle");
          let regionName = expectIdent(p);
          if (regionName.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: regionName._0
            };
          }
          expect(p, "RAngle");
          params.push({
            node: {
              name: paramName$1,
              paramType: {
                node: {
                  TAG: "RegionHandleParam",
                  _0: mode,
                  _1: regionName._0
                },
                loc: paramLoc
              }
            },
            loc: paramLoc
          });
          if (current(p).value === "Comma") {
            advance(p);
          }
          continue;
      }
    };
  };
  let e = parseParams();
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  expect(p, "RParen");
  let returnType;
  if (current(p).value === "Arrow") {
    advance(p);
    let ty = parseFieldType(p);
    returnType = ty.TAG === "Ok" ? ty._0 : undefined;
  } else {
    returnType = undefined;
  }
  let effects;
  if (current(p).value === "Effects") {
    let effs = parseEffects(p);
    effects = effs.TAG === "Ok" ? effs._0 : undefined;
  } else {
    effects = undefined;
  }
  let e$1 = expect(p, "LBrace");
  if (e$1.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e$1._0
    };
  }
  let body = parseBlock(p);
  if (body.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: body._0
    };
  }
  let e$2 = expect(p, "RBrace");
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        node: {
          TAG: "FunctionDecl",
          _0: {
            name: name._0,
            params: params,
            returnType: returnType,
            effects: effects,
            lifetimeConstraints: [],
            body: body._0
          }
        },
        loc: startLoc
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: e$2._0
    };
  }
}

function parseImportRegion(p) {
  let startLoc = current(p).loc;
  advance(p);
  expect(p, "Region");
  let regionName = expectIdent(p);
  if (regionName.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: regionName._0
    };
  }
  expect(p, "From");
  let moduleName = expectString(p);
  if (moduleName.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: moduleName._0
    };
  }
  let fields = [];
  if (current(p).value === "LBrace") {
    advance(p);
    let parseFields = () => {
      while (true) {
        if (current(p).value === "RBrace") {
          return {
            TAG: "Ok",
            _0: undefined
          };
        }
        let field = parseFieldDecl(p);
        if (field.TAG !== "Ok") {
          return {
            TAG: "Error",
            _0: field._0
          };
        }
        fields.push(field._0);
        continue;
      };
    };
    let e = parseFields();
    if (e.TAG === "Ok") {
      expect(p, "RBrace");
    }
  }
  return {
    TAG: "Ok",
    _0: {
      node: {
        TAG: "ImportRegionDecl",
        _0: {
          regionName: regionName._0,
          moduleName: moduleName._0,
          expectedFields: fields
        }
      },
      loc: startLoc
    }
  };
}

function parseExportRegion(p) {
  let startLoc = current(p).loc;
  advance(p);
  expect(p, "Region");
  let regionName = expectIdent(p);
  if (regionName.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: regionName._0
    };
  }
  expect(p, "Semicolon");
  return {
    TAG: "Ok",
    _0: {
      node: {
        TAG: "ExportRegionDecl",
        _0: {
          regionName: regionName._0
        }
      },
      loc: startLoc
    }
  };
}

function parseMemoryDecl(p) {
  let startLoc = current(p).loc;
  advance(p);
  let name = expectIdent(p);
  if (name.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: name._0
    };
  }
  expect(p, "LBrace");
  let initialPages = {
    contents: 0
  };
  let maximumPages = {
    contents: undefined
  };
  let isShared = {
    contents: false
  };
  let placements = [];
  let parseMemBody = () => {
    while (true) {
      let match = current(p).value;
      if (typeof match === "object") {
        return {
          TAG: "Error",
          _0: {
            message: "Unexpected token in memory declaration",
            loc: current(p).loc
          }
        };
      }
      switch (match) {
        case "Place" :
          advance(p);
          let placeLoc = current(p).loc;
          let regionName = expectIdent(p);
          if (regionName.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: regionName._0
            };
          }
          expect(p, "At");
          let offset = parseExprPrec(p, 0);
          if (offset.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: offset._0
            };
          }
          expect(p, "Semicolon");
          placements.push({
            node: {
              regionName: regionName._0,
              offset: offset._0
            },
            loc: placeLoc
          });
          continue;
        case "Initial" :
          advance(p);
          expect(p, "Colon");
          let n = expectInt(p);
          if (n.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: n._0
            };
          }
          initialPages.contents = n._0;
          expect(p, "Semicolon");
          continue;
        case "Maximum" :
          advance(p);
          expect(p, "Colon");
          let n$1 = expectInt(p);
          if (n$1.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: n$1._0
            };
          }
          maximumPages.contents = n$1._0;
          expect(p, "Semicolon");
          continue;
        case "Shared" :
          advance(p);
          isShared.contents = true;
          expect(p, "Semicolon");
          continue;
        case "RBrace" :
          return {
            TAG: "Ok",
            _0: undefined
          };
        default:
          return {
            TAG: "Error",
            _0: {
              message: "Unexpected token in memory declaration",
              loc: current(p).loc
            }
          };
      }
    };
  };
  let e = parseMemBody();
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  expect(p, "RBrace");
  return {
    TAG: "Ok",
    _0: {
      node: {
        TAG: "MemoryDecl",
        _0: {
          name: name._0,
          initialPages: initialPages.contents,
          maximumPages: maximumPages.contents,
          isShared: isShared.contents,
          placements: placements
        }
      },
      loc: startLoc
    }
  };
}

function parseInvariantDecl(p) {
  let startLoc = current(p).loc;
  advance(p);
  let name = expectIdent(p);
  if (name.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: name._0
    };
  }
  expect(p, "LBrace");
  let regions = [];
  let proposition = {
    contents: undefined
  };
  let tactic = {
    contents: undefined
  };
  let parseInvBody = () => {
    while (true) {
      let match = current(p).value;
      if (typeof match === "object") {
        return {
          TAG: "Error",
          _0: {
            message: "Unexpected token in invariant",
            loc: current(p).loc
          }
        };
      }
      switch (match) {
        case "Across" :
          advance(p);
          expect(p, "Colon");
          let parseRegionList = () => {
            while (true) {
              let r = expectIdent(p);
              if (r.TAG !== "Ok") {
                return {
                  TAG: "Error",
                  _0: r._0
                };
              }
              regions.push(r._0);
              if (current(p).value !== "Comma") {
                return {
                  TAG: "Ok",
                  _0: undefined
                };
              }
              advance(p);
              continue;
            };
          };
          let e = parseRegionList();
          if (e.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: e._0
            };
          }
          expect(p, "Semicolon");
          continue;
        case "Holds" :
          advance(p);
          expect(p, "Colon");
          let prop = parseExprPrec(p, 0);
          if (prop.TAG !== "Ok") {
            return {
              TAG: "Error",
              _0: prop._0
            };
          }
          proposition.contents = prop._0;
          expect(p, "Semicolon");
          continue;
        case "Proof" :
          advance(p);
          expect(p, "Colon");
          let match$1 = current(p).value;
          if (typeof match$1 !== "object") {
            switch (match$1) {
              case "TacticBoundsCheck" :
                advance(p);
                tactic.contents = "BoundsCheck";
                break;
              case "TacticLinearity" :
                advance(p);
                tactic.contents = "Linearity";
                break;
              case "TacticLifetime" :
                advance(p);
                tactic.contents = "Lifetime";
                break;
              case "TacticAliasFreedom" :
                advance(p);
                tactic.contents = "AliasFreedom";
                break;
              case "TacticEffectPurity" :
                advance(p);
                tactic.contents = "EffectPurity";
                break;
            }
          }
          expect(p, "Semicolon");
          continue;
        case "RBrace" :
          return {
            TAG: "Ok",
            _0: undefined
          };
        default:
          return {
            TAG: "Error",
            _0: {
              message: "Unexpected token in invariant",
              loc: current(p).loc
            }
          };
      }
    };
  };
  let e = parseInvBody();
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  expect(p, "RBrace");
  let prop = proposition.contents;
  if (prop !== undefined) {
    return {
      TAG: "Ok",
      _0: {
        node: {
          TAG: "InvariantDecl",
          _0: {
            name: name._0,
            regions: regions,
            proposition: prop,
            proofTactic: tactic.contents
          }
        },
        loc: startLoc
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "Invariant missing 'holds' clause",
        loc: startLoc
      }
    };
  }
}

function parseDeclaration(p) {
  let match = current(p).value;
  if (typeof match === "object") {
    return {
      TAG: "Error",
      _0: {
        message: "Expected declaration (region, import, export, fn, memory, invariant)",
        loc: current(p).loc
      }
    };
  }
  switch (match) {
    case "Region" :
      return parseRegionDecl(p);
    case "Import" :
      return parseImportRegion(p);
    case "Export" :
      return parseExportRegion(p);
    case "Memory" :
      return parseMemoryDecl(p);
    case "Fn" :
      return parseFunctionDecl(p);
    case "Invariant" :
      return parseInvariantDecl(p);
    default:
      return {
        TAG: "Error",
        _0: {
          message: "Expected declaration (region, import, export, fn, memory, invariant)",
          loc: current(p).loc
        }
      };
  }
}

function parseModule(source) {
  let p = {
    tokens: Lexer.tokenize(source),
    pos: 0
  };
  let declarations = [];
  let loop = () => {
    while (true) {
      if (current(p).value === "EOF") {
        return {
          TAG: "Ok",
          _0: {
            declarations: declarations
          }
        };
      }
      let decl = parseDeclaration(p);
      if (decl.TAG !== "Ok") {
        return {
          TAG: "Error",
          _0: decl._0
        };
      }
      declarations.push(decl._0);
      continue;
    };
  };
  return loop();
}

export {
  make,
  current,
  peek,
  loc,
  advance,
  expect,
  expectIdent,
  expectInt,
  expectString,
  located,
  parsePrimitiveType,
  parseFieldType,
  parsePrimary,
  binOpPrecedence,
  parseExprPrec,
  parseExpr,
  parseRegionTarget,
  parseFieldPath,
  parseStatement,
  parseBlock,
  parseFieldDecl,
  parseRegionDecl,
  parseEffects,
  parseFunctionDecl,
  parseImportRegion,
  parseExportRegion,
  parseMemoryDecl,
  parseInvariantDecl,
  parseDeclaration,
  parseModule,
}
/* No side effect */
