// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lexer from "../../src/parser/Lexer.mjs";
import * as Parser from "../../src/parser/Parser.mjs";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let passCount = {
  contents: 0
};

let failCount = {
  contents: 0
};

function test(name, f) {
  try {
    f();
    passCount.contents = passCount.contents + 1 | 0;
    console.log(`  ✓ ` + name);
    return;
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === Stdlib_Exn.$$Error) {
      failCount.contents = failCount.contents + 1 | 0;
      console.error(`  ✗ ` + name + `: ` + Stdlib_Option.getOr(obj._1.message, "unknown error"));
      return;
    }
    throw obj;
  }
}

function assertEqual(a, b, msg) {
  if (Primitive_object.notequal(a, b)) {
    return Stdlib_Exn.raiseError(msg);
  }
}

function assertTrue(v, msg) {
  if (!v) {
    return Stdlib_Exn.raiseError(msg);
  }
}

function assertOk(result) {
  if (result.TAG === "Ok") {
    return result._0;
  }
  let err = result._0;
  return Stdlib_Exn.raiseError(`Parse failed at ` + err.loc.line.toString() + `:` + err.loc.col.toString() + `: ` + err.message);
}

let exampleMinimal = `
region Empty {
  value: i32,
}
`;

let exampleEmpty = ``;

let exampleCommentsOnly = `// This file has only comments
// No declarations at all
`;

let example01 = `
region Vec2 {
  x: f32,
  y: f32,
}

region Players[100] {
  hp: i32 where 0 <= hp <= 9999,
  pos: @Vec2,
  name_ptr: ptr<u8>,
  target: opt<@Players>,
}

fn move_player(
  players: &mut region<Players>,
  idx: i32,
  dx: f32,
  dy: f32
) -> i32
  effects ReadRegion(Players), WriteRegion(Players), ReadRegion(Vec2), WriteRegion(Vec2)
{
  region.get $players[idx] .hp -> current_hp;
  if current_hp <= 0 {
    return 0;
  }
  region.get $players[idx] .pos.x -> old_x;
  region.set $players[idx] .pos.x, old_x + dx;
  return 1;
}
`;

console.log("--- Lexer Tests ---");

test("tokenize minimal region", () => {
  let tokens = Lexer.tokenize(exampleMinimal);
  assertTrue(tokens.length !== 0, "Should produce tokens");
  let first = tokens[0];
  assertEqual(first.value, "Region", "First token should be Region keyword");
});

test("tokenize empty string", () => {
  Lexer.tokenize(exampleEmpty);
  assertTrue(true, "Should not crash on empty input");
});

test("tokenize comments only", () => {
  Lexer.tokenize(exampleCommentsOnly);
  assertTrue(true, "Should handle comments-only input");
});

test("tokenize region.get compound token", () => {
  let tokens = Lexer.tokenize("region.get $players .hp -> val;");
  let hasRegionGet = tokens.some(t => t.value === "RegionGet");
  assertTrue(hasRegionGet, "Should tokenize region.get as compound token");
});

test("tokenize region.set compound token", () => {
  let tokens = Lexer.tokenize("region.set $players .hp, 100;");
  let hasRegionSet = tokens.some(t => t.value === "RegionSet");
  assertTrue(hasRegionSet, "Should tokenize region.set as compound token");
});

test("tokenize pointer types", () => {
  let tokens = Lexer.tokenize("ptr<u8>");
  let hasPtr = tokens.some(t => t.value === "Ptr");
  assertTrue(hasPtr, "Should tokenize ptr keyword");
});

test("tokenize opt type", () => {
  let tokens = Lexer.tokenize("opt<@Players>");
  let hasOpt = tokens.some(t => t.value === "Opt");
  assertTrue(hasOpt, "Should tokenize opt keyword");
});

test("tokenize effect keywords", () => {
  let tokens = Lexer.tokenize("effects ReadRegion(Players), WriteRegion(Players)");
  let hasEffects = tokens.some(t => t.value === "Effects");
  let hasRead = tokens.some(t => t.value === "EffReadRegion");
  let hasWrite = tokens.some(t => t.value === "EffWriteRegion");
  assertTrue(hasEffects, "Should tokenize effects keyword");
  assertTrue(hasRead, "Should tokenize ReadRegion");
  assertTrue(hasWrite, "Should tokenize WriteRegion");
});

test("tokenize example01 without error", () => {
  let tokens = Lexer.tokenize(example01);
  assertTrue(tokens.length > 50, "Example01 should produce many tokens");
});

console.log("--- Parser Tests ---");

test("parse minimal region", () => {
  let module_ = assertOk(Parser.parseModule(exampleMinimal));
  assertEqual(module_.declarations.length, 1, "Should have 1 declaration");
  let decl = module_.declarations[0];
  let r = decl.node;
  if (r.TAG !== "RegionDecl") {
    return Stdlib_Exn.raiseError("Expected RegionDecl");
  }
  let r$1 = r._0;
  assertEqual(r$1.name, "Empty", "Region name should be Empty");
  assertEqual(r$1.fields.length, 1, "Should have 1 field");
});

test("parse empty file", () => {
  let result = Parser.parseModule(exampleEmpty);
  if (result.TAG === "Ok") {
    return assertEqual(result._0.declarations.length, 0, "Empty file should have 0 decls");
  }
});

test("parse comments-only file", () => {
  let result = Parser.parseModule(exampleCommentsOnly);
  if (result.TAG === "Ok") {
    return assertEqual(result._0.declarations.length, 0, "Comments only should have 0 decls");
  }
});

test("parse region with constraint", () => {
  let module_ = assertOk(Parser.parseModule(`
region Health[100] {
  hp: i32 where 0 <= hp <= 9999,
  max_hp: i32,
}
`));
  assertEqual(module_.declarations.length, 1, "Should have 1 declaration");
  let decl = module_.declarations[0];
  let r = decl.node;
  if (r.TAG !== "RegionDecl") {
    return Stdlib_Exn.raiseError("Expected RegionDecl");
  }
  let r$1 = r._0;
  assertEqual(r$1.name, "Health", "Region name should be Health");
  assertTrue(Stdlib_Option.isSome(r$1.instanceCount), "Should have instance count");
  assertEqual(r$1.fields.length, 2, "Should have 2 fields");
});

test("parse function with effects", () => {
  let module_ = assertOk(Parser.parseModule(`
fn read_hp(
  players: &region<Players>,
  idx: i32
) -> i32
  effects ReadRegion(Players)
{
  region.get $players[idx] .hp -> val;
  return val;
}
`));
  assertEqual(module_.declarations.length, 1, "Should have 1 declaration");
  let decl = module_.declarations[0];
  let f = decl.node;
  if (f.TAG !== "FunctionDecl") {
    return Stdlib_Exn.raiseError("Expected FunctionDecl");
  }
  let f$1 = f._0;
  assertEqual(f$1.name, "read_hp", "Function name should be read_hp");
  assertTrue(Stdlib_Option.getOr(f$1.effects, []).length >= 1, "Should have at least 1 effect");
  assertTrue(f$1.body.length >= 1, "Should have body statements");
});

test("parse example01 (single module)", () => {
  let module_ = assertOk(Parser.parseModule(example01));
  assertTrue(module_.declarations.length >= 3, "Example01 should have at least 3 declarations");
});

test("region fields have correct types", () => {
  let module_ = assertOk(Parser.parseModule(`
region TestTypes {
  a: i32,
  b: f64,
  c: u8,
  d: ptr<i32>,
}
`));
  let decl = module_.declarations[0];
  let r = decl.node;
  if (r.TAG !== "RegionDecl") {
    return Stdlib_Exn.raiseError("Expected RegionDecl");
  }
  let r$1 = r._0;
  assertEqual(r$1.fields.length, 4, "Should have 4 fields");
  assertEqual(r$1.fields[0].node.name, "a", "First field should be 'a'");
});

test("parse memory declaration", () => {
  let module_ = assertOk(Parser.parseModule(`
memory Main {
  pages: 256,
  max_pages: 1024,
}
`));
  assertEqual(module_.declarations.length, 1, "Should have 1 declaration");
  let decl = module_.declarations[0];
  let match = decl.node;
  if (match.TAG === "MemoryDecl") {
    return;
  } else {
    return Stdlib_Exn.raiseError("Expected MemoryDecl");
  }
});

console.log("");

console.log(`--- Results: ` + passCount.contents.toString() + ` passed, ` + failCount.contents.toString() + ` failed ---`);

if (failCount.contents > 0) {
  Stdlib_Exn.raiseError("Tests failed");
}

export {
  passCount,
  failCount,
  test,
  assertEqual,
  assertTrue,
  assertOk,
  exampleMinimal,
  exampleEmpty,
  exampleCommentsOnly,
  example01,
}
/*  Not a pure module */
