# SPDX-License-Identifier: MPL-2.0
name: OSSF Scorecard

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    permissions:
      security-events: write
      id-token: write
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@e0caf11508a3989574713c78f5f444f2ce5e33ef
    secrets: inherit
